const $=s=>document.querySelector(s);let state={user:null,daily:null,active:null,privateNote:'',page:'home',sort:'level'};let tick=null;
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'เกิดข้อผิดพลาด');return d}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2600)}
function fmt(m){m=Math.max(0,Math.floor(m));return `${Math.floor(m/60)}h ${m%60}m`}
function remain(ms){ms=Math.max(0,ms);const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function shell(content){return `<header class="topbar"><div class="topinner"><div class="mini-logo">⚔️ Study Quest</div><nav class="nav">${[['home','🏠 Home'],['study','⏱️ Study'],['events','🎰 Events'],['leader','🏆 Leaderboard'],['friends','🤝 Friends'],['profile','👤 Profile']].map(([p,t])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${t}</button>`).join('')}</nav><button class="btn" onclick="logout()">Logout</button></div></header><main class="wrap">${content}</main>`}
function render(){if(!state.user){document.body.innerHTML=`<div class="landing"><div class="hero"><div class="logo">STUDY QUEST</div><p class="tag">เปลี่ยนเวลาเรียนให้กลายเป็น XP • Level • Streak • Quest</p><div class="actions"><button class="btn primary" onclick="auth('login')">เข้าสู่ระบบ</button><button class="btn" onclick="auth('register')">สร้างบัญชี</button></div><p class="muted">🎁 สมาชิกใหม่ได้รับ 3 Free Spins</p></div></div>`;return}let c=state.page==='home'?home():state.page==='study'?study():state.page==='events'?events():state.page==='leader'?leader():state.page==='friends'?friends():profile(state.user,true);document.body.innerHTML=shell(c);}
function auth(mode){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="card form"><h2>${mode==='login'?'เข้าสู่ระบบ':'สร้างบัญชี'}</h2>${mode==='register'?`<div class="field"><label>Username</label><input id="au"></div><div class="field"><label>Password (อย่างน้อย 6 ตัว)</label><input id="ap" type="password"></div><div class="field"><label>Confirm Password</label><input id="ac" type="password"></div>`:`<div class="field"><label>Username</label><input id="au"></div><div class="field"><label>Password</label><input id="ap" type="password"></div>`}<div class="actions"><button class="btn" onclick="this.closest('.modal').remove()">ยกเลิก</button><button class="btn primary" onclick="submitAuth('${mode}')">${mode==='login'?'Login':'สร้างบัญชี'}</button></div></div></div>`)}
async function submitAuth(mode){try{const body={username:$('#au').value,password:$('#ap').value};if(mode==='register')body.confirmPassword=$('#ac').value;const d=await api('/api/'+(mode==='login'?'login':'register'),{method:'POST',body:JSON.stringify(body)});state.user=d.user;await refresh();document.querySelector('.modal')?.remove();render();toast(mode==='register'?'🎁 ได้รับ 3 Free Spins!':'ยินดีต้อนรับกลับ!')}catch(e){toast(e.message)}}
async function logout(){await api('/api/logout',{method:'POST'});state={user:null,daily:null,active:null,page:'home'};render()}
async function refresh(){const d=await api('/api/me');Object.assign(state,d);}
function home(){const u=state.user,d=state.daily, pct=Math.min(100,d.minutes/u.dailyGoal*100), xpPct=Math.min(100,(u.xp-(u.level-1)**2*100)/(u.nextXp-(u.level-1)**2*100)*100);return `<h1>Dashboard</h1><div class="grid"><div class="card stat"><div class="muted">🔥 Current Streak</div><div class="v">${u.streak} Days</div></div><div class="card stat"><div class="muted">⭐ Level</div><div class="v">${u.level}</div></div><div class="card stat"><div class="muted">⚡ XP</div><div class="v">${u.xp}</div></div><div class="card stat"><div class="muted">🎰 Spins</div><div class="v">${u.spins}</div></div></div><div class="grid2 section"><div class="card"><h2>TODAY'S PROGRESS</h2><div style="display:flex;justify-content:space-between"><b>${d.minutes} / ${u.dailyGoal} minutes</b><span>${Math.round(pct)}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><p class="${d.goal_met?'notice good':'muted'}">${d.goal_met?'🎉 DAILY GOAL COMPLETE!':'🎯 เรียนให้ครบ Daily Goal เพื่อเพิ่ม Streak'}</p><button class="btn primary" onclick="go('study')">▶ START STUDY</button></div><div class="card"><h2>⭐ LEVEL ${u.level}</h2><div class="xp"><span>${u.xp} XP</span><span>Next: ${u.nextXp} XP</span></div><div class="progress"><i style="width:${xpPct}%"></i></div><p class="muted">⏱️ เรียนรวม ${fmt(u.totalMinutes)} • 📅 ${u.studyDays} วันที่เรียน</p><span class="badge">${u.category}</span></div></div>`}
function study(){const u=state.user,a=state.active;return `<h1>⏱️ Study</h1><div class="card timer">${a?`<div class="badge">SESSION IN PROGRESS</div><div id="clock" class="clock">--:--</div><p class="muted">เริ่ม ${new Date(a.started_at).toLocaleTimeString('th-TH')} • ตั้งไว้ ${a.duration_min} นาที</p><button class="btn danger" onclick="abandon()">ยุติรอบ</button>`:`<div class="muted">Session Time</div><div style="max-width:420px;margin:18px auto"><input id="tm" type="number" min="1" max="720" value="${u.sessionMin}"><p class="muted">นาที</p></div><button class="btn primary" onclick="startTimer()">▶ START STUDY</button>`}</div><div class="grid2 section"><div class="card"><h2>🎯 Daily Goal</h2><p class="muted">${u.dailyGoal} นาที/วัน</p><input id="dg" type="number" min="1" max="1440" value="${u.dailyGoal}"><button class="btn" style="margin-top:10px" onclick="saveSettings()">บันทึก</button></div><div class="card"><h2>📌 กติกา</h2><p class="muted">Session ที่ครบตามเวลาจะถูกตรวจสอบจาก Timestamp ฝั่งเซิร์ฟเวอร์ แล้วจึงให้เวลา + XP +3 Spins</p></div></div>`}
async function startTimer(){try{const min=Number($('#tm').value);const d=await api('/api/timer/start',{method:'POST',body:JSON.stringify({minutes:min})});state.active=d.session;render();runTick()}catch(e){toast(e.message)}}
function runTick(){clearInterval(tick);tick=setInterval(async()=>{if(!state.active)return;const left=state.active.ends_at-Date.now();const el=$('#clock');if(el)el.textContent=remain(left);if(left<=0){clearInterval(tick);await refresh();render();toast('🎉 STUDY SESSION COMPLETE! +XP +3 SPINS');}},500);const el=$('#clock');if(el)el.textContent=remain(state.active.ends_at-Date.now())}
async function abandon(){if(!confirm('ยุติรอบนี้? รอบที่ไม่ครบจะไม่ได้รางวัลเต็ม'))return;await api('/api/timer/abandon',{method:'POST'});state.active=null;render();toast('Session ถูกยุติแล้ว')}
async function saveSettings(){await api('/api/profile',{method:'PUT',body:JSON.stringify({dailyGoal:Number($('#dg').value),sessionMin:state.user.sessionMin,bio:state.user.bio,goal:state.user.goal,learning:state.user.learning})});await refresh();render();toast('บันทึก Daily Goal แล้ว')}
function events(){return `<h1>🎰 Events</h1><div class="card" style="text-align:center"><div id="spinText" class="spin">พร้อมสุ่ม Quest?</div><button class="btn primary" ${state.user.spins<=0?'disabled':''} onclick="spin()">🎰 SPIN (${state.user.spins})</button><p class="muted">ใช้ 1 Spin ต่อการสุ่ม</p></div><div class="grid2 section">${[['☕','Rest Events','พักและรีเฟรชสมอง'],['⚡','Special Events','ภารกิจพัฒนาตัวเอง']].map(x=>`<div class="card"><h2>${x[0]} ${x[1]}</h2><p class="muted">${x[2]}</p></div>`).join('')}</div>`}
async function spin(){const el=$('#spinText');const seq=['🎰 SPINNING...','☕ กำลังค้นหา Event...','🎵 กำลังสุ่ม...','🎮 อีกนิดเดียว...','✨ Almost there...','🎰 STOP!'];let i=0;el.textContent=seq[0];const iv=setInterval(()=>{i++;el.textContent=seq[i%seq.length]},180);setTimeout(async()=>{clearInterval(iv);try{const d=await api('/api/spin',{method:'POST'});state.user.spins=d.spins;el.innerHTML=`🎉 EVENT FOUND<br><small>${d.event.icon} ${d.event.name}<br>${d.event.description}</small>`;render();$('#spinText').innerHTML=`🎉 EVENT FOUND<br><small>${d.event.icon} ${d.event.name}<br>${d.event.description}</small>`}catch(e){toast(e.message)}},1400)}
async function leader(){const d=await api('/api/leaderboard?sort='+state.sort);return `<h1>🏆 Leaderboard</h1><div class="actions" style="justify-content:flex-start"><button class="btn ${state.sort==='level'?'primary':''}" onclick="state.sort='level';renderLeader()">⭐ Level</button><button class="btn ${state.sort==='streak'?'primary':''}" onclick="state.sort='streak';renderLeader()">🔥 Streak</button><button class="btn ${state.sort==='time'?'primary':''}" onclick="state.sort='time';renderLeader()">⏱️ Study Time</button></div><div class="card section"><table class="leader"><thead><tr><th>Rank</th><th>User</th><th>Level</th><th>Streak</th><th>Study Time</th><th>Category</th></tr></thead><tbody>${d.rows.map((u,i)=>`<tr class="clickable" onclick="viewUser(${u.id})"><td>${i<3?['🥇','🥈','🥉'][i]:'#'+u.rank}</td><td><b>${u.username}</b></td><td>Lv.${u.level}</td><td>🔥 ${u.streak}</td><td>${fmt(u.totalMinutes)}</td><td>${u.category}</td></tr>`).join('')}</tbody></table></div>`}
async function renderLeader(){document.body.innerHTML=shell(await leader())}
async function viewUser(id){const d=await api('/api/users/'+id);document.body.innerHTML=shell(profile(d.user,false))}
function profile(u,own){return `<h1>👤 Profile</h1><div class="card"><div class="profileHero"><div><div class="profileName">${u.username}</div><span class="badge">${u.category}</span><div class="streak">🔥 ${u.streak} DAYS STREAK</div><h2>⭐ LEVEL ${u.level}</h2><p class="muted">⚡ ${u.xp} XP • ⏱️ ${fmt(u.totalMinutes)} • 📅 ${u.studyDays} study days</p></div>${!own?`<button class="btn good" onclick="sendFriend(${u.id})">🤝 Add Friend</button>`:''}</div><hr style="border-color:#242b3e"><h3>📣 Public Note</h3><p>${u.bio||'ยังไม่มี Note สาธารณะ'}</p><h3>🎯 Public Goal</h3><p>${u.goal||'ยังไม่ได้แชร์เป้าหมาย'}</p><h3>📚 กำลังเรียน</h3><p>${u.learning||'ยังไม่ได้ระบุ'}</p>${own?`<div class="grid2"><div><h3>แก้ไข Profile</h3><textarea id="bio">${u.bio}</textarea><input id="goal" placeholder="Public Goal" value="${u.goal}"><input id="learning" placeholder="กำลังเรียน" value="${u.learning}" style="margin-top:8px"><button class="btn" style="margin-top:10px" onclick="saveProfile()">บันทึก Public Profile</button></div><div><h3>📝 My Private Notes</h3><textarea id="pn">${state.privateNote}</textarea><button class="btn" style="margin-top:10px" onclick="saveNote()">บันทึก Private Note</button></div></div>`:''}</div>`}
async function saveProfile(){await api('/api/profile',{method:'PUT',body:JSON.stringify({bio:$('#bio').value,goal:$('#goal').value,learning:$('#learning').value,dailyGoal:state.user.dailyGoal,sessionMin:state.user.sessionMin})});await refresh();render();toast('บันทึกแล้ว')}
async function saveNote(){await api('/api/private-note',{method:'PUT',body:JSON.stringify({content:$('#pn').value})});state.privateNote=$('#pn').value;toast('Private Note ถูกบันทึก')}
async function sendFriend(id){try{await api('/api/friends/request',{method:'POST',body:JSON.stringify({userId:id})});toast('ส่ง Friend Request แล้ว')}catch(e){toast(e.message)}}
async function friends(){const d=await api('/api/friends');return `<h1>🤝 Friends</h1><div class="card"><h2>🔎 ค้นหา Username</h2><input id="fq" placeholder="พิมพ์ Username"><button class="btn" style="margin-top:10px" onclick="searchUsers()">ค้นหา</button><div id="results"></div></div><div class="grid2 section"><div class="card"><h2>Friend Requests</h2>${d.incoming.length?d.incoming.map(x=>`<div class="notice" style="margin:8px 0"><b>${x.username}</b> Lv.${x.level}<div style="margin-top:8px"><button class="btn good" onclick="respond(${x.id},true)">รับ</button> <button class="btn danger" onclick="respond(${x.id},false)">ปฏิเสธ</button></div></div>`).join(''):'<div class="empty">ไม่มีคำขอใหม่</div>'}</div><div class="card"><h2>รายชื่อเพื่อน</h2>${d.friends.length?d.friends.map(x=>`<div class="notice clickable" onclick="viewUser(${x.id})" style="margin:8px 0"><b>${x.username}</b> • Lv.${x.level} • 🔥${x.current_streak}</div>`).join(''):'<div class="empty">ยังไม่มีเพื่อน</div>'}</div></div>`}
async function searchUsers(){const d=await api('/api/users/search?q='+encodeURIComponent($('#fq').value));$('#results').innerHTML=d.users.map(u=>`<div class="notice clickable" style="margin-top:8px" onclick="viewUser(${u.id})"><b>${u.username}</b> • Lv.${u.level} • 🔥${u.streak}<button class="btn" style="float:right" onclick="event.stopPropagation();sendFriend(${u.id})">Add</button></div>`).join('')||'<div class="empty">ไม่พบผู้ใช้</div>'}
async function respond(id,accept){await api('/api/friends/respond',{method:'POST',body:JSON.stringify({requestId:id,accept})});render()}
async function go(p){state.page=p;await refresh();render();if(p==='study'&&state.active)runTick()}
(async()=>{try{await refresh();render();if(state.active)runTick()}catch{render()}})();
